services:
  postgresql:
    image: postgres
    container_name: test_project
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: postgres

  redis:
    image: redis:alpine3.19
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
