services:
  postgresql:
    image: postgres
    container_name: test_project
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=slava
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    command: postgres

  redis:
    image: redis:alpine3.19
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
