//* moks - данные для тестирования

export const users = [
  {
    _id: '66ae2f56b4f87bc69acbc5ec',
    index: 0,
    guid: '61f58ebd-2d23-4d72-a435-98a8e78e63a1',
    isActive: false,
    balance: '$3,658.17',
    picture: 'http://placehold.it/32x32',
    age: 39,
    eyeColor: 'brown',
    name: 'Love Snow',
    gender: 'male',
    company: 'PLASMOX',
    email: 'lovesnow@plasmox.com',
    phone: '+1 (958) 586-3516',
    address: '232 Bragg Street, Garnet, Nevada, 3252',
    about:
      'Exercitation labore irure aliqua aute ut id aute. Sunt quis ad minim culpa aliqua aliqua tempor nulla exercitation non. Consequat fugiat non qui sit aute nostrud proident aliqua nostrud. Anim duis ex ea amet esse in pariatur exercitation aute tempor. Sit eiusmod laborum ullamco non et nulla ipsum mollit commodo laboris nostrud dolore.\r\n',
    registered: '2023-02-14T06:58:04 -03:00',
    latitude: 84.362993,
    longitude: -9.746619,
    tags: [
      'adipisicing',
      'quis',
      'proident',
      'ea',
      'est',
      'mollit',
      'consequat',
    ],
    friends: [
      {
        id: 0,
        name: 'Dorothy Lynch',
      },
      {
        id: 1,
        name: 'Hewitt Fernandez',
      },
      {
        id: 2,
        name: 'Sherri Morales',
      },
    ],
    greeting: 'Hello, Love Snow! You have 6 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66ae2f565d5ed600f338593b',
    index: 1,
    guid: '951e0a53-3e07-4e96-9fa9-6a5250b66d6b',
    isActive: true,
    balance: '$2,812.05',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: 'Hodge White',
    gender: 'male',
    company: 'SPORTAN',
    email: 'hodgewhite@sportan.com',
    phone: '+1 (979) 530-2705',
    address: '953 Ashford Street, Dixonville, Wyoming, 9554',
    about:
      'Non ex nostrud occaecat consectetur Lorem Lorem. Anim in amet adipisicing est occaecat exercitation id nostrud ex deserunt mollit aliquip tempor qui. Dolor incididunt occaecat aute in nostrud eu nisi. Minim non est aliqua ea eiusmod nulla minim. Nulla velit enim reprehenderit anim aute ea eu elit amet. Quis labore pariatur quis est id sint ut commodo reprehenderit proident eiusmod veniam magna.\r\n',
    registered: '2023-02-22T10:04:13 -03:00',
    latitude: -71.333363,
    longitude: -95.765936,
    tags: [
      'eiusmod',
      'sunt',
      'eiusmod',
      'velit',
      'excepteur',
      'esse',
      'veniam',
    ],
    friends: [
      {
        id: 0,
        name: 'Amelia Lucas',
      },
      {
        id: 1,
        name: 'Williamson Montgomery',
      },
      {
        id: 2,
        name: 'Acosta Willis',
      },
    ],
    greeting: 'Hello, Hodge White! You have 5 unread messages.',
    favoriteFruit: 'strawberry',
  },
  {
    _id: '66ae2f5629f2e9a10ff166d8',
    index: 2,
    guid: '979d9e2d-77ec-4d64-bb0d-a2b1ee8cbc70',
    isActive: true,
    balance: '$2,953.22',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'green',
    name: 'Sharron Abbott',
    gender: 'female',
    company: 'BITTOR',
    email: 'sharronabbott@bittor.com',
    phone: '+1 (979) 488-3104',
    address: '939 Brighton Court, Rosine, Kentucky, 9164',
    about:
      'Dolor enim sit sint magna exercitation aliqua elit ea consectetur. Sit id excepteur officia sunt est qui Lorem sunt sunt velit eiusmod. Aliqua sunt commodo non est velit minim fugiat veniam do velit ex exercitation. Tempor Lorem occaecat duis veniam eiusmod aliquip qui. Enim eu aliquip non Lorem anim anim enim culpa quis.\r\n',
    registered: '2014-11-14T02:30:43 -03:00',
    latitude: 26.142942,
    longitude: -98.123595,
    tags: ['non', 'ex', 'culpa', 'est', 'consequat', 'ipsum', 'labore'],
    friends: [
      {
        id: 0,
        name: 'Tara Barber',
      },
      {
        id: 1,
        name: 'Michael Wilder',
      },
      {
        id: 2,
        name: 'Jerri Ashley',
      },
    ],
    greeting: 'Hello, Sharron Abbott! You have 4 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '66ae2f56d7ab0b4f2e7f4a4b',
    index: 3,
    guid: 'c9fbd461-7618-4231-9262-e85151e7ae8a',
    isActive: true,
    balance: '$2,806.64',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'blue',
    name: 'Hooper Velasquez',
    gender: 'male',
    company: 'MELBACOR',
    email: 'hoopervelasquez@melbacor.com',
    phone: '+1 (862) 423-3131',
    address: '634 Gerry Street, Vale, Northern Mariana Islands, 1550',
    about:
      'Nulla enim officia ad consectetur veniam ad nulla ea commodo consectetur labore. Commodo do amet sint aliquip ipsum sint commodo pariatur nostrud tempor consectetur. Aliquip fugiat ad enim velit esse exercitation dolor quis nulla proident Lorem consequat esse aliquip. Aliquip enim ipsum ex duis voluptate dolor mollit officia.\r\n',
    registered: '2019-06-12T09:27:14 -03:00',
    latitude: -12.988455,
    longitude: 141.091406,
    tags: ['eu', 'aute', 'cillum', 'nostrud', 'veniam', 'aute', 'esse'],
    friends: [
      {
        id: 0,
        name: 'Carrillo Yates',
      },
      {
        id: 1,
        name: 'Cathy Fuentes',
      },
      {
        id: 2,
        name: 'Karen Chambers',
      },
    ],
    greeting: 'Hello, Hooper Velasquez! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66ae2f564e458486852bfcab',
    index: 4,
    guid: '6d4b9601-73f9-422b-ba79-30ecdd12cd4a',
    isActive: true,
    balance: '$1,375.86',
    picture: 'http://placehold.it/32x32',
    age: 33,
    eyeColor: 'blue',
    name: 'Cohen Crawford',
    gender: 'male',
    company: 'GEEKETRON',
    email: 'cohencrawford@geeketron.com',
    phone: '+1 (872) 511-2560',
    address: '471 Sheffield Avenue, Highland, American Samoa, 6602',
    about:
      'Dolore aliquip minim sit laboris incididunt nisi pariatur deserunt pariatur est nisi labore velit. Elit cupidatat ex quis do consequat adipisicing quis nisi. Officia aute adipisicing fugiat officia magna. Adipisicing id reprehenderit officia mollit eu aliquip magna ea ut nisi adipisicing.\r\n',
    registered: '2019-05-29T10:05:42 -03:00',
    latitude: 68.657543,
    longitude: 126.46005,
    tags: ['proident', 'do', 'do', 'fugiat', 'cupidatat', 'eiusmod', 'ea'],
    friends: [
      {
        id: 0,
        name: 'Mercer Padilla',
      },
      {
        id: 1,
        name: 'Horne Pearson',
      },
      {
        id: 2,
        name: 'Yang Callahan',
      },
    ],
    greeting: 'Hello, Cohen Crawford! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66ae2f56bc0da9252221743d',
    index: 5,
    guid: 'da0ee259-963c-433c-b66e-d8c77bcc7102',
    isActive: false,
    balance: '$1,458.52',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'green',
    name: 'Estes Hoover',
    gender: 'male',
    company: 'ISOSTREAM',
    email: 'esteshoover@isostream.com',
    phone: '+1 (974) 464-2749',
    address: '748 Gold Street, Dundee, Michigan, 1439',
    about:
      'Exercitation consequat eu amet qui pariatur voluptate id sit. Et Lorem cupidatat ea eu tempor elit reprehenderit aliquip enim velit exercitation velit amet sunt. Minim ad sint consectetur sint minim. Excepteur consequat irure ut do eu excepteur exercitation.\r\n',
    registered: '2020-09-18T01:36:14 -03:00',
    latitude: 26.48412,
    longitude: 176.628956,
    tags: [
      'mollit',
      'do',
      'exercitation',
      'officia',
      'aliqua',
      'Lorem',
      'nostrud',
    ],
    friends: [
      {
        id: 0,
        name: 'Tillman Roach',
      },
      {
        id: 1,
        name: 'Josefina Mcbride',
      },
      {
        id: 2,
        name: 'Ola Gallagher',
      },
    ],
    greeting: 'Hello, Estes Hoover! You have 8 unread messages.',
    favoriteFruit: 'strawberry',
  },
]
